services:
  pg:
    image: postgres:14-alpine3.17
    environment:
      - "POSTGRES_DB=${DB_NAME}"
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7.2.5-alpine3.20
    ports:
      - "${REDIS_PORT}:6379"
    container_name: redis_chat_service
    volumes:
      - redis-data:/data

volumes:
  pgdata:
  redis-data: